image: oven/bun:latest

pages:
  stage: deploy
  script:
    - bun install
    - bun run build:pages
    - mv dist public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'